version: "3"
services:

  models:
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - ./isa:/app
    ports:
      - "8001:8000"
    networks:
      - backend
    command: bash -c "mod_wsgi-express start-server --working-directory <project_root_dir> --reload-on-changes <path_to_wsgi.py>/wsgi.py"

networks:
  backend: